name: Build AmneziaWG for ImmortalWrt x86_64
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "ImmortalWrt ${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch}} build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_env:
          - tag: "24.10.5"
            pkgarch: x86_64
            target: x86
            subtarget: 64
            vermagic: "e7e50fbc0aafa7443418a79928da2602" 

    steps:
      - uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: Cache Tools and Kernel
        id: cache-tools-kernel
        uses: actions/cache@v4
        with:
          path: "**"
          key: ${{ runner.os }}-immortal-build-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}
          restore-keys: |
            ${{ runner.os }}-immortal-build-${{ matrix.build_env.tag }}-

      - name: Building kernel and tools
        run: |
          BASE_URL="https://downloads.immortalwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}"
          
          wget $BASE_URL/feeds.buildinfo -O feeds.conf
          
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> ./feeds.conf
          
          ./scripts/feeds update && ./scripts/feeds install -a

          wget $BASE_URL/config.buildinfo -O .config
          
          {
            echo "CONFIG_PACKAGE_kmod-amneziawg=m"
            echo "CONFIG_PACKAGE_amneziawg-tools=y"
            echo "CONFIG_PACKAGE_luci-app-amneziawg=y"
            echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20=m"
            echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=m"
            echo "CONFIG_PACKAGE_kmod-crypto-chacha20poly1305=m"
          } >> .config

          make defconfig

          make tools/install -i -j$(nproc)
          make toolchain/install -i -j$(nproc)

          make target/linux/compile -i -j$(nproc) V=s

          CURRENT_VERMAGIC=`cat ./build_dir/target-*/linux-*/linux-*/.vermagic`
          echo "Detected Vermagic: $CURRENT_VERMAGIC"
          
          if [ "$CURRENT_VERMAGIC" != "${{ matrix.build_env.vermagic }}" ]; then
            echo "Error: Vermagic mismatch! Expected ${{ matrix.build_env.vermagic }} but got $CURRENT_VERMAGIC"
            # Если ты хочешь, чтобы билд не падал, а просто выводил инфо — закомментируй exit 1
            exit 1
          fi

      - name: Build AmneziaWG Packages
        run: |
          make package/kmod-amneziawg/compile V=s
          make package/amneziawg-tools/compile V=s
          make package/luci-app-amneziawg/compile V=s

      - name: Prepare artifacts
        run: |
          mkdir -p awgrelease
          tag_name=${{ github.ref_name }}
          postfix="immortal_${tag_name}_v${{ matrix.build_env.tag }}_${{ matrix.build_env.pkgarch}}"
          
          find bin/ -name "amneziawg-tools*.ipk" -exec cp {} awgrelease/amneziawg-tools_${postfix}.ipk \;
          find bin/ -name "luci-app-amneziawg*.ipk" -exec cp {} awgrelease/luci-app-amneziawg_${postfix}.ipk \;
          find bin/ -name "kmod-amneziawg*.ipk" -exec cp {} awgrelease/kmod-amneziawg_${postfix}.ipk \;

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: awgrelease/*.ipk
